import type { Metadata } from "next";
import { Inter, Manrope, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


// Configuração da Inter (geralmente Sans)
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

// Configuração da Manrope (ex: para títulos)
const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
  display: 'swap',
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//export default function RootLayout({
//  children,
//}: Readonly<{
//  children: React.ReactNode;
//}>) {
//  return (
//    <html
//      lang="en"
//      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//    >
//      <body className="min-h-full flex flex-col">{children}</body>
//    </html>
//  );
//}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${inter.variable} ${manrope.variable}`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}